### ISSUE TITLE
Overall improvement of your code

### ISSUE THREAD

**Issue by philyoun** [henry32144/pggan-tensorflow#4]
Hi, Henry,
 I am the one who asked you about the unused `in_filters` argument in `upsample_function()`. After asking that question, I tried the remaining part of your codes, and I was able to make overall improvement. 
 Some of the major changes are, 1) I made every functions to be `class` instead of function using `def`, so I was able to continue learning even with `@tf.function`. I didn't have to reset `EPOCH` after specific `IMAGE_SIZE` is done. 2) I could also find your effort to make generators/discriminator of certain `IMAGE_SIZE` to be more general(i.e. you tried to make a class 'Discriminator()' that makes `build_4x4_discriminator()`, `build_8x8_discriminator()`, ..., `build_512x512_discriminator()`  in your legacy.ipynb). I'm happy to tell you that I improved your code a little bit.
 I made a minimal, reproducible example colab you can test. https://colab.research.google.com/drive/17BMtWZuF7q-pn8TI6Khjcrpx56si8BF8#scrollTo=8vXHHo7e5Y40 (I made some stupid mistake to put `time.time()` in the wrong place at the last code block, so I can't tell you how long it takes to run the whole code. But definitely not too long, I made it as minimal as possible.)

 As well as major changes to your code, I also added some additional functions, slightly changed the name of variables, so I don't think it is a right thing to ask for pull requests. Maybe I will create my own repository and share the results. I did the whole training for about consecutive 3.5 days, and I got the satisfying final results of 512 x 512 images.
 Surely I will mention to your repository and codes, especially your `EqualizeLearningRate()` layer was great. Thank you Henry!

**Comment by henry32144** [comment]
Hi, philyoun,

Thank you for letting me know about your improvement on this repository. I am not sophisticated in Tensorflow, so It's really good to know about how other people implement the code. I am looking forward to seeing your repository! Please let me know if you finished it.
